services:
  baseball_card_grader_model:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dataset:/app/dataset
      - ./checkpoint:/app/checkpoint
    command: >
      sh -c "python train_model.py ./dataset/ ./checkpoint && 
      python convert_to_onnx.py ./checkpoint/"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ipc: host